# clowder server
clowder:
  image: clowder/clowder:develop
#  environment:
#    CLOWDER_ADMIN: "joe@aol.com"
#    TOOLMANAGER_URI: "http://192.168.99.100:8080"
#    SMTP_HOST: smtp.ncsa.illinois.edu
  ports:
    - "9000:9000"
  links:
    - mongo
    - rabbitmq

# extractors
# wordcount:
#   image: clowder/pygeostreams:2
#   links:
#     - rabbitmq

# mongo database used to store metadata/data
mongo:
  image: mongo:latest
  ports:
    - "27017:27017"
  # volumes:
  #   - clowder/mongo:/data/db

# rabbitmq to connect to extractors
rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"
  # volumes:
  #   - clowder/rabbitmq:/var/lib/rabbitmq
